plugins {
    id 'com.android.application'
}

android {
    namespace 'com.twinstick.controller'
    compileSdk 34

    defaultConfig {
        applicationId "com.twinstick.controller"
        minSdk 28
        targetSdk 34
        versionCode 3
        versionName "1.0"
    }

    buildTypes {
        debug {
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
